# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0002_auto_20160111_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
