# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0003_auto_20160111_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'managed': False},
        ),
    ]
